services:
  postgres:
    hostname: postgres
    image: postgres:latest
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./docker/volumes/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
